drop database if exists taxbenfits;


create database if not exists taxbenfits;



USE taxbenfits;


DROP TABLE if exists ADDRESS_TYPE;

DROP TABLE if exists USER_TYPE;

DROP TABLE if exists ADDRESS;

DROP TABLE if exists USER1;
 
DROP TABLE if exists AGENT;
  
DROP TABLE if exists ORGANIZATION1;
   
DROP TABLE if exists REGISTRATION;
   
DROP TABLE if exists TAX_PAYER;
  
DROP TABLE if exists BANK_ACCOUNT;
 
DROP TABLE if exists TAX_PAYER_DEPEDENT;
 
DROP TABLE if exists FEDRAL_TAX_TRANSACTION;
  
DROP TABLE if exists STATE_TAX_TRANSACTION;


CREATE TABLE ADDRESS_TYPE(ADDRESS_TYPE_ID INTEGER NOT NULL PRIMARY KEY,DESCRIPTION VARCHAR(100) NOT NULL);


CREATE TABLE USER_TYPE(USER_TYPE_ID INTEGER NOT NULL PRIMARY KEY, DESCRIPTION VARCHAR(100));


CREATE TABLE ADDRESS(ADDRESS_ID INTEGER NOT NULL PRIMARY KEY, ADDRESS_TYPE_ID INTEGER NOT NULL REFERENCES ADDRESS_TYPE(ADDRESS_TYPE_ID),
 ADDRESS1 VARCHAR(100) NOT NULL,ADDRESS2 VARCHAR(100), CITY VARCHAR(10) NOT NULL,STATE VARCHAR(20) NOT NULL,COUNTRY VARCHAR(20) NOT NULL, ZIP INTEGER(15) NOT NULL);


CREATE TABLE USER1(USER_ID INTEGER NOT NULL PRIMARY KEY,FIRST_NAME VARCHAR(15) NOT NULL,MIDDLE_NAME VARCHAR(15) ,LAST_NAME VARCHAR(15) NOT NULL, 
 BILLING_ADDRESS_ID INTEGER NOT NULL REFERENCES ADDRESS(ADDRESS_ID),MAILING_ADDRESS_ID INTEGER NOT NULL REFERENCES ADDRESS(ADDRESS_ID), PHYSICAL_ADDRESS_ID INTEGER NOT NULL REFERENCES ADDRESS(ADDRESS_ID));


CREATE TABLE AGENT(AGENT_ID INTEGER NOT NULL PRIMARY KEY,USER_ID INTEGER NOT NULL,
 EIN_NUMBER INTEGER NOT NULL,CONSTRAINT EIN UNIQUE(EIN_NUMBER), OFFICE_ADDRESS_ID INTEGER NOT NULL REFERENCES ADDRESS(ADDRESS_ID));


CREATE TABLE ORGANIZATION1(ORGANIZATION_ID INTEGER NOT NULL PRIMARY KEY,USER_ID INTEGER NOT NULL, ORGANIZATION_NAME VARCHAR(100) NOT NULL,
 EIN_NUMBER INTEGER NOT NULL,CONSTRAINT EIN_ORGANIZATION UNIQUE(EIN_NUMBER),
 ORGANIZATION_ADDRESS_ID INTEGER NOT NULL REFERENCES ADDRESS(ADDRESS_ID));


CREATE TABLE REGISTRATION(REGISTRATION_ID INTEGER NOT NULL PRIMARY KEY,USER_NAME VARCHAR(20) NOT NULL,EMAIL_ADDRESS VARCHAR(30) NOT NULL,
 PHONE_NUMBER VARCHAR(30) NOT NULL,USER_TYPE_ID INTEGER NOT NULL, USER_ID INTEGER NOT NULL REFERENCES USER(USER_ID),PASSWORD VARCHAR(100) NOT NULL);

 
CREATE TABLE TAX_PAYER(TAX_PAYER_ID INTEGER NOT NULL PRIMARY KEY,USER_ID INTEGER NOT NULL,
 SSN INTEGER NOT NULL);

 
CREATE TABLE BANK_ACCOUNT(BANK_ACCOUNT_ID INTEGER NOT NULL,TAX_PAYER_ID INTEGER NOT NULL REFERENCES TAX_PAYER(TAX_PAYER_ID),BANK_NAME VARCHAR(100) NOT NULL,BRANCH_NAME VARCHAR(100) NOT NULL,
 ACCOUNT_NUMBER INTEGER NOT NULL,BANK_ADDRESS_ID INTEGER NOT NULL REFERENCES ADDRESS(ADDRESS_ID),ROUTING_NUMBER INTEGER NOT NULL);

 
CREATE TABLE TAX_PAYER_DEPEDENT(TAX_PAYER_DEPEDENT_ID INTEGER NOT NULL PRIMARY KEY,TAX_PAYER_ID INTEGER NOT NULL REFERENCES TAX_PAYER(TAX_PAYER_ID),
 YEAR INTEGER NOT NULL,MARITAL_STATUS VARCHAR(10) NOT NULL,NUMBER_OF_DEPEDENT INTEGER NOT NULL,DEPENDENT VARCHAR(10) NOT NULL,DEPENDENT_TAX_PAYER_ID INTEGER NOT NULL REFERENCES TAX_PAYER(TAX_PAYER_ID));
 

CREATE TABLE FEDRAL_TAX_TRANSACTION(FEDRAL_TAX_TRANSACTION_ID INTEGER NOT NULL PRIMARY KEY,TAX_PAYER_ID INTEGER NOT NULL REFERENCES TAX_PAYER(TAX_PAYER_ID),YEAR INTEGER NOT NULL,FILER_TYPE_ID INTEGER NOT NULL,
 FILER_USER_ID INTEGER NOT NULL REFERENCES AGENT(AGENT_ID),N_TH_YEAR_OF_TAX_FILLING INTEGER NOT NULL, STATE_NAME VARCHAR(30) NOT NULL,STATE_CODE INTEGER NOT NULL);
 

CREATE TABLE STATE_TAX_TRANSACTION(STATE_TAX_TRANSACTION_ID INTEGER NOT NULL PRIMARY KEY,TAX_PAYER_ID INTEGER NOT NULL REFERENCES TAX_PAYER(TAX_PAYER_ID),YEAR INTEGER NOT NULL,
 FILER_TYPE_ID INTEGER NOT NULL,FILER_USER_ID INTEGER NOT NULL REFERENCES AGENT(AGENT_ID),
 N_TH_YEAR_OF_TAX_FILLING INTEGER NOT NULL,STATE_NAME VARCHAR(30) NOT NULL,STATE_CODE INTEGER NOT NULL);
